### ISSUE TITLE
Update for hyper 0.12?

### ISSUE THREAD

**Issue by FauxFaux** [softprops/hyperlocal#10]
There's a new hyper/tokio out.

They've changed everything, and there's no upgrade documentation.

Uh, strike that. I mean, it'd be *fun* to add support for it!

**Comment by softprops** [comment]
It's on my list of things to do. Pull requests are welcome if you can get to it before I do!

**Comment by dylanmckay** [comment]
I've opened #11, which should do the trick.

**Comment by softprops** [comment]
merged https://github.com/softprops/hyperlocal/pull/11 so closing
