### ISSUE TITLE
SocketIncoming is not exported

### ISSUE THREAD

**Issue by kornelski** [softprops/hyperlocal#31]
`bind_unix` returns `Builder<SocketIncoming>`, but `SocketIncoming` isn't exported from the crate, so I can't name it to return it from my functions, put it in a struct, etc.

**Comment by kornelski** [comment]
It would also be useful if there was possibility of making `SocketIncoming` or the builder from `UnixListener`.

**Comment by softprops** [comment]
I would be open to a pull request to add this
