### ISSUE TITLE
http paths errors

### ISSUE THREAD

**Issue by beckend** [softprops/hyperlocal#48]
I am using it to query podman unix socket and it requires paths such as `http://d/v3.0.0/libpod/pods/json`, which works fine in curl.
But of course such a path is invalid for hyper:
```shell
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUri(InvalidAuthority)'
```

**Comment by kornelski** [comment]
Hyperlocal supports only local filesystem paths. You need to extract filesystem path out of the pseudo-HTTP URL yourself.

**Comment by beckend** [comment]
ok thanks

**Comment by softprops** [comment]
The use case is interesting though. in your example, `http://d/v3.0.0/libpod/pods/json` how does the client/server know what path to bind to?

**Comment by kornelski** [comment]
In `curl` you specify `--unix-socket path` as a separate argument.

**Comment by kornelski** [comment]
In superagent I've used to support `http+unix://<urlencoded-local-path>/<http-abspath>`, `http+unix://%2Fabsolute%2Fpath%2Fto%2Funix.sock/request/path`

**Comment by beckend** [comment]
Well I am saying it's a pattern that deserves to be supported.

**Comment by beckend** [comment]
https://docs.podman.io/en/latest/_static/api.html#operation/PodCreateLibpod

**Comment by kornelski** [comment]
But `curl --unix-socket /run/podman/podman.sock http://d/v3.0.0/libpod/info` is not a URL. Note that `--unix-socket` is one argument, the URL is another. To connect, it's necessary to have both.
