### ISSUE TITLE
RFC: Release 0.9

### ISSUE THREAD

**Issue by onalante-msft** [softprops/hyperlocal#56]
There have been a couple of small quality-of-life improvements since the previous release. What I am personally interested in is the compilation time reduction in the main branch over 0.8. Some of the documentation would need updating to match the fact that features are no longer enabled by default.

**Comment by edmorley** [comment]
@onalante-msft @softprops I'd love to have the compile time improvements too. I've opened #58 for documenting the opt-in features - hopefully that's one step towards being able to release :-)

**Comment by edmorley** [comment]
@softprops Hi :-) I don't suppose you might get a chance to release the new version at some point?

**Comment by jiangliu** [comment]
@softprops A new release is welcomed:)

**Comment by iamjpotts** [comment]
I've opened a PR to upgrade `hyper` to `1.x`: https://github.com/softprops/hyperlocal/pull/65

**Comment by softprops** [comment]
released 0.9.x
