### ISSUE TITLE
get ready for hyper's 0.11 changes

### ISSUE THREAD

**Issue by softprops** [softprops/hyperlocal#6]
some discussion is being had over here https://github.com/hyperium/hyper/issues/126

**Comment by kevincox** [comment]
It appears that these changes have landed.

**Comment by softprops** [comment]
I've already started a local branch for this. The client was actually really easy to implement ( easier than I thought ). The server listener is proving to be more difficult. Mostly because there aren't may examples of documentation of how to customize the server's listening backend with the newer model

**Comment by skinowski** [comment]
Would you mind sharing the client-only changes?

**Comment by softprops** [comment]
Sure I'll push up a branch tonight. In the meantime I reached out to the hyper maintainers to see if I could get some insight on extending the new server model

**Comment by softprops** [comment]
[this](https://github.com/softprops/hyperlocal/blob/async-hyper/src/lib.rs) is what I have so far. I have the client working in an example [here](https://github.com/softprops/hyperlocal/blob/async-hyper/examples/client.rs#L13-L37) still working on getting the server bits line up

**Comment by skinowski** [comment]
Thank you, I've playing around with this code, but I'm getting errors such as:

`
error[E0599]: no method named `build` found for type `hyper::client::Config<uds::UnixSocketConnector, hyper::Body>` in the current scope
   --> src/collector.rs:181:7
    |
181 |                                   .build(&core.handle.as_ref().borrow().clone()))
    |                                    ^^^^^
    |
    = note: the method `build` exists but the following trait bounds were not satisfied:
            `uds::UnixSocketConnector : hyper::client::Connect`
`

I'm on hyper 0.11.2, and it seems like hyper::client::Connect trait needs implementation, not service for the client?

**Comment by softprops** [comment]
Hoping to get a chance to followup this weekend

**Comment by softprops** [comment]
async hyper 0.11 support is now on master. see the examples directory for an example client and server usage
