### ISSUE TITLE
Use either rustfmt.toml or .rustfmt.toml but not both

### ISSUE THREAD

**Issue by szabgab** [softprops/hyperlocal#71]
It seem that in this repository there is both a `rustfmt.toml` and a `.rustfmt.toml` file which is confusing as only one will be used. [See this report](https://rust-digger.code-maven.com/news/rustfmt-stats)

**Comment by softprops** [comment]
> I found that 14,951 of the crates (10.53%) have rustfmt.toml and 5,420 crates (3.81%) have .rustfmt.toml 35 crates have both

Not intentional. I'm prefer the more common `rustfmt.toml` name

**Comment by szabgab** [comment]
I did not think it was intentional :smile:

**Comment by softprops** [comment]
thanks for the heads up
