### ISSUE TITLE
Need to be able to chmod the socket

### ISSUE THREAD

**Issue by njaard** [softprops/hyperlocal#9]
After I call `Http::bind()`, I need to be able to chmod the file descriptor appropriately.

In theory, something like this:

    let s = hyperlocal::server::Http::new()
      .bind(&address["unix:".len()..], new_service)?;
    libc::fchmod(s.listener.as_raw_fd(), 0o777);

But this isn't possible because `s.listener` is not `pub`.

**Comment by moosingin3space** [comment]
Maybe a function `Http::bind_with_permissions` could be used to atomically bind and chmod?

**Comment by njaard** [comment]
POSIX doesn't offer an atomic "bind and chmod" for unix domain sockets, and I think a more generalized solution of "let me access the low level object" is warranted.

**Comment by moosingin3space** [comment]
Such as an `as_raw_fd` function on `Server`?

**Comment by softprops** [comment]
@moosingin3space @njaard I just published 0.5.0 which includes a change to expose [this](https://docs.rs/hyperlocal/0.5.0/hyperlocal/server/struct.Server.html#method.local_addr)
